#!/usr/bin/perl

# The MIT License (MIT)
#
# Copyright (c) 2014 Gil Gonçalves
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

use strict;
use warnings;


my $graph_size  = $ENV{'GRAPH_SIZE'} || 1;
my $custom_char = $ENV{'CUSTOM_CHAR'};


chomp( @ARGV = <STDIN> ) unless @ARGV;

my @list = sort { $a <=> $b } @ARGV;

for my $i ( @ARGV ) {
    printf( "%s\n", show($i, $list[-1], $graph_size) );
}


sub show {
    my $num        = shift;
    my $max        = shift;
    my $graph_size = shift;

    my @graph;

    if ($custom_char) {
        @graph = ($custom_char);
    }
    else {
        @graph = qw{ ▏ ▎ ▍ ▌ ▋ ▊ ▉ █};
    }

    if ( $graph_size - 1 == 0) { $graph_size = 1; }
    else                       { $graph_size--;   }

    my $bar_num = ( $num * ( scalar(@graph) * $graph_size ) ) / $max;

    my $str = $graph[-1] x int($bar_num / scalar(@graph) );
    $str   .= $graph[ int($bar_num % (scalar(@graph) ) ) ];

    return $str;
}
