#!/usr/bin/perl

use strict;
use warnings;

# Default value, this will to the console size
my $size = $ENV{'TERM_SIZE'} || 1;
my $custom_char = $ENV{'CUSTOM_CHAR'};


chomp( @ARGV = <STDIN> ) unless @ARGV;

my @list = sort { $a <=> $b } @ARGV;

for my $i ( @ARGV ) {
    printf( "%s\n", show($i, $list[-1], $size) );
}

sub show {
    my $num  = shift;
    my $max  = shift;
    my $size = shift;

    my @graph;

    if ($custom_char) {
        @graph = ($custom_char);
    }
    else {
        @graph = qw{ ▏ ▎ ▍ ▌ ▋ ▊ ▉ █};
    }

    if ( $size - 1 == 0) { $size = 1; }
    else                 { $size--;   }

    my $bar_num = ( $num * ( scalar(@graph) * $size ) ) / $max;

    my $str = $graph[-1] x int($bar_num / scalar(@graph) );
    $str   .= $graph[ int($bar_num % (scalar(@graph) ) ) ];

    return $str;
}
